version: 0.1

phases:
  pre_build:
    commands:
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $(cat /tmp/build_id.out)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $(cat /tmp/build_tag.out)
artifacts:
  files: /tmp/build.json
  discard-paths: yes

# version: 0.1
# phases:
#   pre_build:
#     commands:
#       - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
#       - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
#       - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
#       - $(aws ecr get-login)
#   build:
#     commands:
#       - docker build --tag "$(cat /tmp/build_tag.out)" .
#   post_build:
#     commands:
#       - docker push "$(cat /tmp/build_tag.out)"
# artifacts:
#   files: /tmp/build.json
#   discard-paths: yes
